[package]
name = "repo-status"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]

[dependencies]
clap = "2"
colored = "1.6"
failure = "0.1"
futures = "0.2"
git2 = "0.7"
itertools = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.2"
xml-rs = "0.7"
